name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sound: [ "", "NOSOUND=1", "MMOD=1"]
        flashcard: [ "", "FLASHCARD=1" ]
        desquid: [ "", "DESQUID=1" ]
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker pull devkitpro/devkitarm
        docker run -p 4000:80 --name devkitarm devkitpro/devkitarm || true
        mkdir -p /opt/devkitpro
        docker cp devkitarm:/opt/devkitpro /opt || true
        docker cp devkitarm:/opt/devkitpro/tools /opt/devkitpro || true
        PATH=/opt/devkitpro/tools/bin:$PATH
        cd PNEO
        make ${{matrix.sound}} ${{matrix.flashcard}} ${{matrix.desquid}}
    - uses: actions/upload-artifact@v3.0.0
      with:
        name: "${{matrix.sound}}.${{matrix.flshcard}}.${{matrix.desquid}}"
        path: PNEO/PNEO.nds


